default: &default
  host:  host: <%= `docker-machine ip bmxend` %>
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: bicycle

test:
  <<: *default
  database: izzy_test

production:
  adapter: postgresql
  encoding: unicode
  database: production
  pool: 5
  username: izzatbamieh1
  password: izzy678362!78Qu@ndel_D@shboArD%
